### ISSUE TITLE
About preprocess function

### ISSUE THREAD

**Issue by kmakino14** [Durenlab/LINGER#15]
Dear all,

First of all, thanks for developing useful tools for analysis.

I tried to run the PBMC tutorial, but I have a question about the inputs used in the function preprocess().
What is the ATAC.txt described in extract_overlap_regions_LINGER.sh?
What are the following two text files?
　TFName = pd.read_csv(GRNdir+'TFName.txt',header=None)
　Match2 = pd.read_csv(GRNdir+'Match2.txt',sep='\t')

Thanks!

Best,
KM

**Comment by amssyqy** [comment]
Thanks for pointing out the problems.
1. I updated the PBMC tutorial https://github.com/Durenlab/LINGER/blob/main/docs/PBMC.md
The usage is 
```python
preprocess(TG_pseudobulk,RE_pseudobulk,GRNdir,genome,method,outdir,workdir)
```
2. Also, I updated the software to version 1.49
Please update the software by
```sh
pip install LingerGRN==1.49
```
extract_overlap_regions_LINGER.sh will automatically be updated after this step
3. About 'TFName.txt' and 'Match2.txt'. They are included in the provided data 'data_bulk.tar.gz'
```sh
Datadir=/path/to/LINGER/# the directory to store the data please use the absolute directory. Example: Datadir=/zfs/durenlab/palmetto/Kaya/SC_NET/code/github/combine/data/
mkdir $Datadir
cd $Datadir
wget --load-cookies /tmp/cookies.txt "https://drive.usercontent.google.com/download?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.usercontent.google.com/download?id=1lAlzjU5BYbpbr4RHMlAGDOh9KWdCMQpS'  -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1lAlzjU5BYbpbr4RHMlAGDOh9KWdCMQpS" -O data_bulk.tar.gz && rm -rf /tmp/cookies.txt
tar -xzf data_bulk.tar.gz
```
GRNdir is $Datadir/data_bulk

**Comment by kmakino14** [comment]
I also could not find extract_overlap_regions_LINGER.sh when I did the update to version 1.49. I could proceed downstream analysis using extract_overlap_regions_LINGER.sh that was previously uploaded.

LINGER_tr.training() function contains for loop, which is computationally expensive in the environment where it is used, and I think some users would benefit if it could be computed in parallel for each chromosome.  

There were several typographical errors.
・LL_net.cell_type_specific_trans_reg(GRNdir,adata_RNA,ATAC_file,celltype,outdir)
'ATAC_file' is not required.
・box_comp(TFName=TFName,adata_RNA=adata_RNA,celltype1=celltype1,celltype2=celltype2,datatype=datatype, regulon_score=TF_activity,. save=True, outdir=outdir)
'label' is not required.

**Comment by amssyqy** [comment]
> Dear all,
> 
> Thank you for developing this interesting tool for GRN inference.
> 
> I tried to install version 1.49 using pip and it does not install `extract_overlap_regions_LINGER.sh` but only `extract_overlap_regions_baseline.sh` and `extract_overlap_regions_scNN.sh`.
> 
> Furthermore, looking at the code for the `preprocess` function in v1.49, I think there are still some problems with the paths to these bash scripts.
> 
> By copying `extract_overlap_regions_baseline` into the working directory, the baseline method works but I'm not sure which method it corresponds to in the LINGER paper (bulkNN?). Can you elaborate a bit more on this please?
> 
> Thank you for your help!
> 
> Best
> 
> LH

Thanks for using LINGER~ 
1. We updated the software to 1.52. We use Python code to replace the shell script extract_overlap_regions*.sh. We updated the tutorial.
2. Your understanding is correct, baseline represents bulkNN. We added it to the tutorial.
Thanks for your time~
Qiueyue

**Comment by amssyqy** [comment]
> I also could not find extract_overlap_regions_LINGER.sh when I did the update to version 1.49. I could proceed downstream analysis using extract_overlap_regions_LINGER.sh that was previously uploaded.
> 
> LINGER_tr.training() function contains for loop, which is computationally expensive in the environment where it is used, and I think some users would benefit if it could be computed in parallel for each chromosome.
> 
> There were several typographical errors. ・LL_net.cell_type_specific_trans_reg(GRNdir,adata_RNA,ATAC_file,celltype,outdir) 'ATAC_file' is not required. ・box_comp(TFName=TFName,adata_RNA=adata_RNA,celltype1=celltype1,celltype2=celltype2,datatype=datatype, regulon_score=TF_activity,. save=True, outdir=outdir) 'label' is not required.

Thanks for using LINGER. 
1. We updated the software to 1.52. We use Python code to replace the shell script extract_overlap_regions*.sh.  
2. We are still working on parallel computation for training.
3. We updated the tutorial and corrected the typo as follows: `LL_net.cell_type_specific_trans_reg(GRNdir,adata_RNA,celltype,outdir)` and `box_comp(TFName,adata_RNA,celltype1,celltype2,datatype,regulon_score,save,outdir)`
Thanks for your time~
Qiuyue
