### ISSUE TITLE
Error in load_TFbinding()

### ISSUE THREAD

**Issue by myylee** [Durenlab/LINGER#32]
Hi there,

Thanks for the great method and package! 

I encountered this error when running the preprocessing step. It stopped at load_TFbinding(), saying that there are unmatched items between Element_name_idx and motif_binding.index. 

I think it is likely a formatting issue, but I am having a hard time figuring out what's the issue. Any thought/recommendation for what might have caused this? 

Thank you very much!

<img width="518" alt="Screen Shot 2024-05-17 at 9 45 55 AM" src="https://github.com/Durenlab/LINGER/assets/66084077/6d38201a-ff05-4cc7-99ef-9352f376daa1">

**Comment by amssyqy** [comment]
Could you print the `RE_pseudobulk`? I think maybe the reason is row names format is not match with chr:start-end.

**Comment by myylee** [comment]
I figured it out. There are more features saved in 'Peaks.txt' than the rows I have in RE_pseudobulk. There was an error in my metacell generation step that resulted in less features. 

Thanks for the speedy response anyways!
