### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by mbensouda** [Durenlab/LINGER#48]
Hi! Is there a way to get access to the source code, I am curious to know what is in the pseudo_bulk function for example!

**Comment by XiaoKaixuan12333** [comment]
you can go to the  the  location of  package  and find the source code. like _./lib/python3.9/site-packages/LINGER_

**Comment by mbensouda** [comment]
thank you! that is helpful! are you working on a documentation? 
Thank you for providing the package, it is very helpful!
